### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by tauseefrehman2** [lvamsavarthan/goquotes-api#2]

**Comment by tauseefrehman2** [comment]
hi, i'm using api for demo purpose but from last 4 to 5 hours it's not working please resolve the issue

**Comment by lvamsavarthan** [comment]
Hello Tauseef ur Rehman,
It's good to hear from you that you are using my API. This api is hosted at
heroku under free tier. It seems that the free tier limit has exceeded, so
I would request you to clone and host your version of the API. Google for
the instructions on how to deploy at heroku.

Thanks ❤️

>

**Comment by lvamsavarthan** [comment]
Hello Tauseef ur Rehman,It's good to hear from you that you are using my API. This api is hosted at heroku under free tier. It seems that the free tier limit has exceeded, so I would request you to clone and host your version of the API. Google for the instructions on how to deploy at heroku.
Thanks ❤️

**Comment by tauseefrehman2** [comment]
can you send please helping material on how to get project from github and upload on heroku. actually i'm android developer
